### ISSUE TITLE
knx read first value

### ISSUE THREAD

**Issue by farizmaw** [vapourismo/knx-go#10]
Hello,
I would like an example to read the initial values from the gateway with sensors in C # (Visual Studio).
I found an example that only gives the new values (after the values are changed), but I also need the first values.
Many Thanks
Fariz

**Comment by vapourismo** [comment]
This is a Go library.

In general getting the first group value in KNX means listening for new values and then stopping when it was received.

**Comment by farizmaw** [comment]
Thanks, could you please give me a link to download it ? because when I googled it I could not know the right one.
