### ISSUE TITLE
DPT 17.001 for scenes 

### ISSUE THREAD

**Issue by korpa** [vapourismo/knx-go#27]
Could you please add DPT 17.001 needed for scenes?

**Comment by vapourismo** [comment]
I am lacking the time and necessity to implement that at the moment. Pull requests are very welcome, though.

**Comment by korpa** [comment]
Ok. Will give it a try. Any hint where to find the KNX specs?

**Comment by vapourismo** [comment]
[KNX Standard](https://my.knx.org/shop/product?product_type_category=knx_specifications&product_type=knx-specifications)
