### ISSUE TITLE
DPT 251.600

### ISSUE THREAD

**Issue by MitchSUEW** [vapourismo/knx-go#34]
Hi,
will there be a support for DPT 251.600, 6 bytes. It's a RGBW LED connected through a DALI KNX adapter from Hager (TXA664D).
Thanks,
Mitch

**Comment by vapourismo** [comment]
I currently don't have any plans to implement it. 
Pull requests are welcome, though. Documentation is [here](https://www.knx.org/wAssets/docs/downloads/Certification/Interworking-Datapoint-types/03_07_02-Datapoint-Types-v02.01.02-AS.pdf) (section 6.18 covers DPT 251.600).

**Comment by vapourismo** [comment]
If you want to give this a shot yourself, there are plenty of PRs that added new DPTs. I think they act as a good base guidance. Otherwise feel free to reach to me directly, if you have more questions.

**Comment by MitchSUEW** [comment]
Thx. I don't think I'm capable to do so.(at least for the time being). But I'm confident there's someone out there...... :-)

**Comment by korpa** [comment]
@MitchSUEW I added DPT 251.600 in #4.

As soon as @vapourismo accepted the PR you should be able to use it.

**Comment by MitchSUEW** [comment]
Wow, that’s awesome. Looking forward to it.

**Comment by korpa** [comment]
@MitchSUEW: @vapourismo accepted the pull request yesterday so DPT 251.600 support is in the master. A `go get github.com/vapourismo/knx-go` in your project should download the latest version.

An example how it works can be found in #41
