### ISSUE TITLE
Update telegraf's import to newest knx-go version

### ISSUE THREAD

**Issue by alexander-zimmermann** [vapourismo/knx-go#37]
Hey Ole, do you know what we need to do that telefgraf update their `go.mod` to our newest version?

**Comment by vapourismo** [comment]
Have you tried to open a PR with their repo?

**Comment by alexander-zimmermann** [comment]
Just run `go get github.com/influxdata/telegraf && go list -m all` and create a PR out of that? Not sure what I've have to do ;-)

**Comment by vapourismo** [comment]
If you're not sure how to do it, or can't find how to do it, I am sure just opening an issue will do eventually.
