### ISSUE TITLE
Missing datatypes

### ISSUE THREAD

**Issue by tomcat166** [vapourismo/knx-go#45]
Several data types are still missing (like flow related 12.1200 f.e.) . Would be nice to see them all implemented.

[https://www.knx.org/wAssets/docs/downloads/Certification/Interworking-Datapoint-types/03_07_02-Datapoint-Types-v02.02.01-AS.pdf](https://www.knx.org/wAssets/docs/downloads/Certification/Interworking-Datapoint-types/03_07_02-Datapoint-Types-v02.02.01-AS.pdf)

**Comment by vapourismo** [comment]
Happy to answer any question you might have in relation to implementing these if you're interested in doing that. That's all I can offer for now.
