### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by mobilarte** [vapourismo/knx-go#51]
Hi,

I started to add some missing DPTs and to do some clean-up by following the specifications (units, allowed ranges, ...).

I also realized that the MulticastLoopback is disabled by default when using `net.ListenMulticastUDP`.

What would be the best procedure for you to integrate all these changes? Changes made so far are [in this branch](https://github.com/mobilarte/knx-go/tree/mobilarte). Would you be available to discuss this?

Thank you very much for your help.

**Comment by vapourismo** [comment]
I think the best course of action is to split them up into topical changes and raise PRs for each.

**Comment by mobilarte** [comment]
Thank you, will do!
