### ISSUE TITLE
Implement DESCRIPTION_REQUEST

### ISSUE THREAD

**Issue by theobarrague** [vapourismo/knx-go#55]
I want to send a DESCRIPTION_REQUEST over IP Gateway.
I can't find an implementation, did you implemented it ? If no, I can help

**Comment by mobilarte** [comment]
DESCRIPTION_REQUEST or DIAGNOSTIC_REQUEST are not implemented here. I have it on my todo list, but I have currently a pull request that needs to be fixed (Multicast behavior on Windows).

I have an experimental copy of this implementation with more DPTs, where I also rewrote the parsing of DIBs including DESCRIPTION_REQUESTs. It is available at [knx-exp](https://github.com/mobilarte/knx-exp). Feel free to test it.

**Comment by vapourismo** [comment]
@mobilarte Want me to assign you this issue for tracking?

**Comment by mobilarte** [comment]
This will probably not be necessary. I have just added a PR for DESCRIPTION_REQUEST with a few cosmetic fixes. Thank you for reviewing.

**Comment by vapourismo** [comment]
This has been addressed in #56 thanks to @mobilarte.
