### ISSUE TITLE
cemi.NewGroupAddrString() does not report error with some wrong addresses

### ISSUE THREAD

**Issue by cespedes** [vapourismo/knx-go#60]
Some uses of cemi.NewGroupAddrString() do not return errors, but it should.  For example:

- cemi.NewGroupAddrString("123/foobar")
- cemi.NewGroupAddrString("1000/2000/3000")

Thank you,

Juan

**Comment by mobilarte** [comment]
Yes, it is assumed that the individual and group addresses are correct. I just made a pull request that may fix this by returning an error if the string could not be parsed properly.

**Comment by vapourismo** [comment]
Closed by #61
