### ISSUE TITLE
DPT242 changes discussion

### ISSUE THREAD

**Issue by korpa** [vapourismo/knx-go#66]
Hi @vapourismo,

I added two comments to 2cc5ef29e187e043995e78e1712070240c2b639d. What is your opinion on these?

**Comment by vapourismo** [comment]
I believe in this case the conversion from and to floating point numbers should not be done by `knx-go`. The datapoint type uses 16-bit integers and that should be reflected on the Go struct.

If you want, you can add methods that extract the axis values as floats, but the struct itself should not store them as such.
