### ISSUE TITLE
New DPT types

### ISSUE THREAD

**Issue by reejinbouk** [vapourismo/knx-go#7]
Hello, is there a list with supported DPT types?
I found only DPT1 and DPT9 at dpt package.
Thank you

**Comment by vapourismo** [comment]
The `dpt` package provides only these two example implementations.

You don't depend on the `dpt` package, because the `Data` field of [GroupEvent](https://godoc.org/github.com/vapourismo/knx-go/knx#GroupEvent) is a byte slice. So you can marshal them on your own.
