### ISSUE TITLE
will knx-go support KNX IP Secure ?

### ISSUE THREAD

**Issue by ldfandian** [vapourismo/knx-go#94]
Just to support using a keyfile to protect TCP/IP connection.

https://support.knx.org/hc/en-us/articles/115003378505-Workflow-Preparation

Similar thing in XKNX (python knx client lib):
![image](https://github.com/user-attachments/assets/b126794e-8a4a-48c8-81f4-d2c71fc1a066)

**Comment by vapourismo** [comment]
I have no plans on implementing this myself. Though PRs are welcome :)
